import esbuild from "esbuild";
import process from "process";
import module from "module";

const builtins = module.builtinModules.filter(m => !m.startsWith("_"));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: false,
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	// Post-build: Remove dynamic script loading from Ace editor (security review requirement)
	const fs = await import("fs");
	let contents = fs.readFileSync("main.js", "utf8");
	contents = contents.replace(
		`exports2.loadScript = function(path2, callback) {
        var head = dom.getDocumentHead();
        var s = document.createElement("script");
        s.src = path2;
        head.appendChild(s);
        s.onload = s.onreadystatechange = function(_2, isAbort) {
          if (isAbort || !s.readyState || s.readyState == "loaded" || s.readyState == "complete") {
            s = s.onload = s.onreadystatechange = null;
            if (!isAbort)
              callback();
          }
        };
      };`,
		`exports2.loadScript = function(path2, callback) { /* disabled for security */ };`
	);
	// Remove XMLHttpRequest from Ace editor's net module (plugin scanner disclosure)
	contents = contents.replace(
		`exports2.get = function(url, callback) {
        var xhr = new XMLHttpRequest();
        xhr.open("GET", url, true);
        xhr.onreadystatechange = function() {
          if (xhr.readyState === 4) {
            callback(xhr.responseText);
          }
        };
        xhr.send(null);
      };`,
		`exports2.get = function(url, callback) { /* disabled: use bundled resources */ };`
	);
	fs.writeFileSync("main.js", contents);
	process.exit(0);
} else {
	await context.watch();
}