import esbuild from "esbuild";
import process from "process";
import module from "module";

const builtins = module.builtinModules.filter(m => !m.startsWith("_"));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: false,
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	// Post-build: Stub out Ace editor's dynamic network helpers (security scanner flags)
	const fs = await import("fs");
	let contents = fs.readFileSync("main.js", "utf8");
	contents = contents.replace(
		/exports2\.loadScript\s*=\s*function\s*\([^)]*\)\s*\{[\s\S]*?document\.createElement\("script"\)[\s\S]*?\n\s{6}\};/,
		`exports2.loadScript = function() { /* disabled: all resources are bundled */ };`
	);
	contents = contents.replace(
		/exports2\.get\s*=\s*function\s*\([^)]*\)\s*\{[\s\S]*?XMLHttpRequest[\s\S]*?\n\s{6}\};/,
		`exports2.get = function() { /* disabled: use bundled resources */ };`
	);
	fs.writeFileSync("main.js", contents);
	process.exit(0);
} else {
	await context.watch();
}